version: '3'
services:
  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile
    volumes:
      - ./nest:/app
      - /app/node_modules
    ports:
      - 3010:3010
    command: npm run start:dev
